import csv
import json
import math
import random
import itertools
import statistics
from pathlib import Path
from .dataset import dump, ROOT, SEED

def metrics(rows,method):
    tp = fp = tn = fn = abstained = missing = correct = 0
    for r in rows:
        if method not in r["predictions"]:
            missing += 1
            continue
        p,y = r["predictions"][method],r["gold_label"]
        if p is None:
            abstained += 1
            # Conservative recall includes positive abstentions in FN.
            fn += int(y)
        else:
            correct += int(p==y)
            tp += int(p and y); fp += int(p and not y)
            tn += int(not p and not y); fn += int(not p and y)
    n = len(rows)
    available = n-missing
    return {"n":n,"available":available,"correct":correct,"tp":tp,"fp":fp,"tn":tn,"fn":fn,"abstained":abstained,"missing":missing,
        "accuracy":correct/n if n else None,"coverage":(available-abstained)/n if n else None,
        "covered_accuracy":correct/(available-abstained) if available>abstained else None,
        "precision":tp/(tp+fp) if tp+fp else 0,"recall":tp/(tp+fn) if tp+fn else 0,
        "f1":2*tp/(2*tp+fp+fn) if 2*tp+fp+fn else 0}

def correctness(r,m):
    return m in r["predictions"] and r["predictions"][m] is not None and r["predictions"][m]==r["gold_label"]

def paired(rows,a,b,resamples=5000):
    groups = {}
    for r in rows:
        groups.setdefault(r["program"],[]).append(r)
    names = sorted(groups)
    rng = random.Random(SEED)
    diffs = []
    for _ in range(resamples):
        sample = [r for n in rng.choices(names,k=len(names)) for r in groups[n]]
        diffs.append(sum(int(correctness(r,a))-int(correctness(r,b)) for r in sample)/len(sample))
    diffs.sort()
    win = sum(correctness(r,a) and not correctness(r,b) for r in rows)
    loss = sum(correctness(r,b) and not correctness(r,a) for r in rows)
    n = win+loss
    p = min(1.,2*sum(math.comb(n,i) for i in range(min(win,loss)+1))/(2**n)) if n else 1.
    # Exact sign-flip randomization at program level preserves variant dependence.
    group_deltas = [sum(int(correctness(r,a))-int(correctness(r,b)) for r in groups[name]) for name in names]
    observed = abs(sum(group_deltas))
    assignments = list(itertools.product((-1,1),repeat=len(names)))
    cluster_p = sum(abs(sum(s*d for s,d in zip(signs,group_deltas))) >= observed for signs in assignments)/len(assignments)
    return {"a":a,"b":b,"a_only_correct":win,"b_only_correct":loss,"accuracy_difference":sum(int(correctness(r,a))-int(correctness(r,b)) for r in rows)/len(rows),
        "cluster_bootstrap_95_ci":[diffs[int(.025*resamples)],diffs[min(resamples-1,int(.975*resamples))]],"mcnemar_exact_p":p,"cluster_randomization_two_sided_p":cluster_p,"clusters":len(names),"resamples":resamples}

def analyze(directory):
    directory = Path(directory)
    rows = [json.loads(x) for x in (directory/"results.jsonl").read_text().splitlines()]
    methods = sorted({m for r in rows for m in r["predictions"]})
    summary = {"splits":{},"paired_test":[],"limits":["Only 8 test program clusters: exploratory confidence intervals", "31 small public algorithms, possible training contamination", "Jev direct is same decision model, not a general LLM judge", "Combined collection batches do not establish per-method cold latency/cost", "Controls generated by this experiment, not supplied by QuixBugs", "No equivalence guarantee or production-code evidence"]}
    for split in ("development","validation","test","all"):
        selected = [r for r in rows if split=="all" or r["split"]==split]
        summary["splits"][split] = {m:metrics(selected,m) for m in methods}
    test = [r for r in rows if r["split"]=="test"]
    if "meaningci-jsd" in methods:
        summary["paired_test"] = [paired(test,"meaningci-jsd",m) for m in ("jev-direct","tests-budget-3","tests-full","ci-tests-full","meaningci-label")]
    regressions = [r for r in rows if r["gold_label"]]
    summary["oracle_diagnostics"] = {"label":"ORACLE evaluator-only, NOT a method", "regression_programs":len(regressions),"selected_inputs_witness":sum(r["oracle_selected_inputs"] for r in regressions),"predicate_witness":sum(r["oracle_probe_coverage"] for r in regressions)}
    summary["collection"] = {"captured_pairs":sum("jev" in r for r in rows),"failures":sum("jev_error" in r for r in rows),"resolved_models":sorted({r["jev"]["model"] for r in rows if "jev" in r}),
        "native_usage": [r["jev"].get("usage") for r in rows if "jev" in r], "method_specific_cost":None,"general_llm_judge":"Unavailable: no configured credentials; not substituted"}
    captures = [r["jev"] for r in rows if "jev" in r]
    engine = sorted(j["engine_time_ms"] for j in captures if isinstance(j.get("engine_time_ms"),(float,int)))
    wall = sorted(j["ui_wall_ms"] for j in captures if isinstance(j.get("ui_wall_ms"),(float,int)))
    summary["collection"].update({"native_input_tokens":sum((j.get("usage") or {}).get("input_tokens",0) for j in captures),
        "native_output_tokens":sum((j.get("usage") or {}).get("output_tokens",0) for j in captures),
        "native_decisions":sum(len(j["vectors"]) for j in captures),"engine_p50_ms":statistics.median(engine) if engine else None,
        "engine_p95_ms":engine[min(len(engine)-1,math.ceil(.95*len(engine))-1)] if engine else None,
        "ui_p50_ms":statistics.median(wall) if wall else None,"ui_p95_ms":wall[min(len(wall)-1,math.ceil(.95*len(wall))-1)] if wall else None,
        "ui_latency_samples":len(wall),"price_estimate_usd":None,"price_estimate_reason":"No current billing tariff verified; native tokens reported, no fabricated money estimate"})
    known = correct = decisive = decisive_correct = 0
    for r in rows:
        if "jev" not in r:continue
        for i,o in enumerate(r["oracle_observations"]):
            for version in ("A","B"):
                truth = o[version]
                if truth is None:continue
                known += 1
                v = r["jev"]["vectors"]["%s_%02d" % (version,i)]
                label = "YES" if truth else "NO"
                correct += v["top"]==label
                if v["top"]!="UNKNOWN" and v["probabilities"][v["top"]]>=.65:
                    decisive += 1;decisive_correct += v["top"]==label
    summary["probe_understanding"] = {"known_binary_observations":known,"top_label_correct":correct,"accuracy":correct/known if known else None,
        "confident_observations":decisive,"confident_correct":decisive_correct,"confident_accuracy":decisive_correct/decisive if decisive else None,
        "scope":"Descriptive all-split observations; repeated contexts are correlated; not an independent held-out metric"}
    dump(directory/"summary.json",summary)
    with (directory/"metrics.csv").open("w",newline="",encoding="utf-8") as file:
        writer = csv.DictWriter(file,fieldnames=["split","method"]+list(metrics(rows,methods[0])))
        writer.writeheader()
        for split,values in summary["splits"].items():
            for method,m in values.items():writer.writerow(dict(split=split,method=method,**m))
    text = ["# MeaningCI Code benchmark report", "", "## Hypothesis", "", "Behavioral decision probes may detect code regressions with fewer false alarms than syntax changes, and may complement tests. They must beat simpler direct decisions to justify their complexity.", "", "## Dataset and methodology", "", "Pinned QuixBugs revision `4257f44b0ff1181dedaedee6a447e133219fcebf`. All 31 JSON-compatible programs: 31 original defects plus 62 mechanically generated preserving controls. Nine graph-object programs are explicitly excluded by the initial adapter. Program-disjoint 15/8/8 development/validation/test split. Code comments/docstrings removed symmetrically, including alternate corrected implementations. Three inputs chosen by input-only hash; four fixed behavioral predicates per input. Providers never receive gold expected outputs or labels.", "", "## Held-out results", "", "| Method | Correct / 24 | Accuracy | TP | FP | Abstentions | Missing | F1 |", "|---|---:|---:|---:|---:|---:|---:|---:|"]
    for method,m in summary["splits"]["test"].items():
        text.append("| %s | %d / %d | %.1f%% | %d | %d | %d | %d | %.3f |" % (method,m["correct"],m["n"],100*m["accuracy"],m["tp"],m["fp"],m["abstained"],m["missing"],m["f1"]))
    text += ["", "Missing provider measurements are not predictions; methods with no measurements are omitted. Abstention counts as incorrect for conservative primary accuracy; coverage and covered accuracy are in summary.json. F1 counts positive abstentions as false negatives. Negative abstentions affect conservative accuracy and coverage, not FP.", "", "## Paired analysis", ""]
    for stat in summary["paired_test"]:
        text.append("- %s minus %s: accuracy difference %.3f, program-cluster 95%% CI [%.3f, %.3f], exact McNemar p=%.4f, exact program-level sign-flip p=%.4f; discordant wins/losses %d/%d." % (stat["a"],stat["b"],stat["accuracy_difference"],*stat["cluster_bootstrap_95_ci"],stat["mcnemar_exact_p"],stat["cluster_randomization_two_sided_p"],stat["a_only_correct"],stat["b_only_correct"]))
    text += ["", "Eight held-out clusters give low statistical power. Tests share pairs within a program; McNemar's pair-independence assumption is imperfect here. Bootstrap clusters preserve dependence. Multiple comparisons are exploratory, not confirmatory.", "", "## Ablations and probe coverage", "", "Compare direct judgment, label flips and full distributions on the same batch/model; compare three-input execution with the full official input suite. Fixed confidence gate 0.65; JSD threshold chosen on validation only, saved in frozen_thresholds.json. ORACLE input coverage: %d/%d original defects; ORACLE predicate coverage: %d/%d. These upper-bound diagnostics are evaluator-only and not retrieval/model predictions." % (summary["oracle_diagnostics"]["selected_inputs_witness"],len(regressions),summary["oracle_diagnostics"]["predicate_witness"],len(regressions)), "", "## Failures and cost", "", "Every pair has a trace including source/candidate execution, expected outputs (evaluator only), native vectors if measured, exceptions and timeouts. logs/failures.json preserves upstream fixture mismatches, timeouts and provider errors. Combined batches share code context and collection overhead. Raw native usage and capture wall time are retained; standalone per-method costs/latencies and a general-purpose LLM baseline are not measured.", "", "## Limitations", ""]
    text += ["- "+x for x in summary["limits"]]
    if captures:
        c=summary["collection"]
        text += ["", "## Measured collection resource usage", "", "%d native Jev requests / %d native decisions; %d input tokens and %d output tokens. Combined-batch engine p50 %.1f ms, p95 %.1f ms; UI collection p50 %.1f ms, p95 %.1f ms (%d timed captures; two manual-inspection/recovery captures excluded). These are combined experimental batches, not standalone method service latency. No invoice/tariff was verified; monetary cost remains unavailable." % (len(captures),c["native_decisions"],c["native_input_tokens"],c["native_output_tokens"],c["engine_p50_ms"],c["engine_p95_ms"],c["ui_p50_ms"],c["ui_p95_ms"],c["ui_latency_samples"]), "", "## Interpretation and next design", "", "The fixed input-only predicates miss many exact-value changes even under perfect interpretation. The 0.65 reliability gate plus requiring every remaining probe to be determinate produces many abstentions; this is an honest coverage limit, not a PASS. Distribution shifts can also flag preserving controls. Source A and candidate B are jointly visible, and source answers may change with candidate context; source-independent reuse has not been validated. Do not deploy this battery as an autonomous CI gate. Prefer execution tests; investigate direct Jev as supplementary triage, with its missed defects and uncertainty retained. A future source-grounded scenario generator needs a new protocol and independent production-code benchmark, rather than retuning these test cases."]
    text += ["", "## Conclusions", ""]
    if "meaningci-jsd" not in methods:
        text += ["Execution baselines measured; Jev collection has not been completed. No claim about MeaningCI code detection is supported yet."]
    else:
        main = summary["splits"]["test"]["meaningci-jsd"]
        direct = summary["splits"]["test"]["jev-direct"]
        full = summary["splits"]["test"]["tests-full"]
        text += ["MeaningCI JSD correctly classified %d/%d held-out pairs, direct Jev %d/%d, and full execution tests %d/%d. These small public-program results do not establish production readiness or a commercial advantage. %s" % (main["correct"],main["n"],direct["correct"],direct["n"],full["correct"],full["n"],"The added probe/distribution architecture did not beat direct judgment in conservative accuracy." if main["accuracy"]<=direct["accuracy"] else "A numerical advantage over direct judgment needs the reported paired uncertainty and external replication before claiming improvement.")]
    (directory/"report.md").write_text("\n".join(text)+"\n",encoding="utf-8")
    return summary
